### ISSUE TITLE
R package

### ISSUE THREAD

**Issue by jjchern** [paulgp/bartik-weight#1]
Thanks for putting together the Stata command; it's quite helpful for understanding the paper as well.

I just reimplemented the code in R: https://github.com/jjchern/bartik.weight. If you're interested, I can submit an RP and put the package in the current repo (maybe in an `R-package` folder).

Also, I think there's a typo on page 9 of the paper. The residual projection matrix should be `M_D = I - D(D'D)^{-1}D'`. The last transpose is missing in the paper.

**Comment by paulgp** [comment]
Wow, that's excellent! I would love it if we could pull it into the repo -- can you submit an RP? It would be great if you can include some documentation + a test case (either using one of the datasets or your own example).

**Comment by jjchern** [comment]
Great! I just submit an RP for the package and two test cases.
