### ISSUE TITLE
Weighting matrix is often too large; use sparse weights instead? 

### ISSUE THREAD

**Issue by jagman88** [paulgp/bartik-weight#5]
I am using the `R` version of the code, and I am finding that for moderately large datasets (e.g. >100,000 observations), the creation of the weighting matrix in the function `bw` produces non-sparse matrices that are much, much larger than memory allows. 

Could these weights matrices be created as sparse matrices? For example, when no weights are given the function calls: 
```
  if (is.null(weight)) {
    weight = diag(n)
  }
```
but the `weight` line could be replaced with `weight = .sparseDiagonal(n)` or `weight = sparseMatrix(1:n, 1:n)`, both from the `Matrix` package. Since sparse matrices can be operated on in the same way as non-sparse matrices, this shouldn't cause any further issues, I think.

**Comment by jjchern** [comment]
That's a good idea. Just need to make sure that it plays well with the c++ code. Or maybe Rcpp has some way to handle sparse matrix inputs. I probably won't have time to update it in the short run. If you want to take a crack at it, a PR is more than welcome. Also, I might be wrong but the typical Bartik-shift application is done at the region-year level, so even with detailed data at, for example, the U.S. county-level, 100,000 observations seems quite a lot.

**Comment by jagman88** [comment]
Ah, I didn't realize you were running c++ under the hood (but I guess that explains why I can't see the main function anywhere...). I'm not familiar with c++, so I'm not sure I can handle that part, but I'll do some playing with the `R` code and see what adding sparse matrices does.

You're right, but in my case I'm constructing a Bartik-shift instrument at the county level (~700 or so counties), with annual data for 15 years, and then I have multiple separate households per county. ~20,000 households (with different lengths) yields 100,000+ observations (often many more than that).

**Comment by paulgp** [comment]
You'll likely need to rewrite the code to handle that many entries -- that's a pretty large matrix in the end. Like @jjchern mentioned, something with sparse matrices may work. @jagman88 , if you want to try and rewrite the code, I'm happy to pull the request in once you are able to do it, but I'm not sure either of us are going to be able to update it in the short-run.

Alternatively, you could try doing this in Python or Matlab -- the formulas are all in the paper and should be straightforward to implement (and may be faster in either of those languages).

**Comment by jagman88** [comment]
I've moved to projecting out the control variables in an initial step using the `lmer`/`lfe` packages, which handles large regressions more efficiently. But thanks for the suggestions and the help.
